/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sabaylang;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        SabayLangApp classUnderTest = new SabayLangApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
