# Default port is 8080.
# The ${PORT:8080} syntax tells Spring to use the environment variable "PORT" (required by hosting providers)
# or default to 8080 if the variable is not set.
server.port=${PORT:8080}
